### ISSUE TITLE
Этапы и объекты для логистической карты (США)

### ISSUE THREAD

**Issue by rust1kk** [MattHartfield/LogisticMap#1]
Логистическая карта должна быть изображена на карте выбранной
страны. На карте необходимо отметить и указать город и предприятие на
которых осуществляется этап с указание самого этапа (возможно указание
нескольких точек, где осуществляются выбранный этап). Все точки этапов
должны быть соединены стрелками, по которым осуществляется логистика.
Если какой-либо этапов в текущей стране не осуществляется на схеме
указывается что этап выполняется в другой стране с указанием страны и
предприятий из нее.

**Comment by MattHartfield** [comment]
Closed as irrelevant.
